// constants.js
const CONSTANTS = Object.freeze({
  USERNAME_REGEX: /^[a-zA-Z0-9\-\_\.\+\@]+$/,
  PASSWORD_MIN_LENGTH: 8,
  HAS_UPPERCASE_REGEX: /[A-Z]/,
  HAS_LOWERCASE_REGEX: /[a-z]/,
  HAS_NUMBERS_REGEX: /[0-9]/,
  HAS_SPECIAL_CHAR_REGEX: /[ !"#$%&'()*+,-./:;<=>?@\[\\\]^_`{|}~]/,
  SANITIZE_FILTER: { allowedTags: [], allowedAttributes: {} }, //strict sanitization filter, strips all types of tages from input
  GA_REGEX: /<script.*src="https:\/\/www\.googletagmanager\.com\/gtag\/js\?id=G-[A-Z0-9]+".*<\/script>/,
  INSPECTLET_REGEX: /window\.__insp\s*=\s*window\.__insp\s*\|\|\s*\[\];.*inspectlet\.js\?wid=\d+/s,
  CLARITY_REGEX: /<script[^>]*>\s*\(function\([^)]*\)\{[\s\S]*?["']https:\/\/www\.clarity\.ms\/tag\/["']\s*\+\s*[a-zA-Z0-9]+[\s\S]*?\}\)\([^)]*\);\s*<\/script>/s,
  EMPTY_STRING: '',
  AI_ATTRIBUTE: '\n\n\t\- Summary generated by AI',
  DEFAULT_COMMENT_LIMIT: 10,
  CLAMP_COMMENT_MIN: 1,
  CLAMP_COMMENT_MAX: 50,
  EMAIL_REGEX: /^[a-zA-Z0-9][a-zA-Z0-9._%+-]*[a-zA-Z0-9]@[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$/,
  TAGS_REGEX: /[^a-zA-Z0-9-_]/g,
  /**
  * Enum for privilege levels used to determine user roles.
  * @readonly
  * @enum {number}
  * @property {number} WEBMASTER - Full administrative privileges (level 1)
  * @property {number} MODERATOR - Moderation privileges (level 2)
  * @property {number} EDITOR - Can write and submit content (level 3)
  */
  PRIVILEGE_LEVELS_ENUM: {
      WEBMASTER : 1,
      MODERATOR : 2,
      EDITOR: 3
    }
});

module.exports = { CONSTANTS };
